1:
	pdflatex -shell-escape patc_kokkos_2019.tex

all:
	pdflatex -shell-escape patc_kokkos_2019.tex
	pdflatex -shell-escape patc_kokkos_2019.tex

clean:
	rm -rf patc_kokkos_2019.aux
	rm -rf patc_kokkos_2019.log
	rm -rf patc_kokkos_2019.nav
	rm -rf patc_kokkos_2019.out
	rm -rf patc_kokkos_2019.snm
	rm -rf patc_kokkos_2019.toc
	rm -rf patc_kokkos_2019.vrb

